export const GET_PROPERTIES = 'GET_PROPERTIES';
export const REMOVE_PROPERTY = 'REMOVE_PROPERTY';
export const GET_CATEGORY = 'GET_CATEGORY';
export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES';
export const CLEAR_LOADING = 'CLEAR_LOADING';
export const GET_SEARCH_NAME = 'GET_SEARCH_NAME';
export const CLEAR_SEARCH_CATEGORIES = 'CLEAR_SEARCH_CATEGORIES';
